"""
Django settings for coin_counter project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# ==============================================================================
# КРИТИЧЕСКИЕ НАСТРОЙКИ - проверяем на None
# ==============================================================================

# Bank Integration
CLIENT_ID = os.getenv("CLIENT_ID")
if not CLIENT_ID:
    raise ValueError("CLIENT_ID must be set in .env file")

JWT_TOKEN = os.getenv("JWT_TOKEN")
if not JWT_TOKEN:
    raise ValueError("JWT_TOKEN must be set in .env file")

BANK_ACCOUNTS = os.getenv('BANK_ACCOUNTS', '').split(',')
if not BANK_ACCOUNTS or BANK_ACCOUNTS == ['']:
    raise ValueError("BANK_ACCOUNTS must be set in .env file")

BANK_BIC = os.getenv("BANK_BIC")
if not BANK_BIC:
    raise ValueError("BANK_BIC must be set in .env file")

# Telegram Integration
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
if not TELEGRAM_BOT_TOKEN:
    raise ValueError("TELEGRAM_BOT_TOKEN must be set in .env file")

TELEGRAM_CHAT_IDS = [
    int(cid.strip()) 
    for cid in os.getenv("TELEGRAM_CHAT_IDS", "").split(",") 
    if cid.strip().isdigit()
]
if not TELEGRAM_CHAT_IDS:
    raise ValueError("TELEGRAM_CHAT_IDS must be set in .env file with valid chat IDs")

# Google Sheets Integration
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
if not GOOGLE_SHEET_ID:
    raise ValueError("GOOGLE_SHEET_ID must be set in .env file")

creds_path = os.getenv("GOOGLE_SHEETS_CREDENTIALS")
if not creds_path:
    raise ValueError("GOOGLE_SHEETS_CREDENTIALS must be set in .env file")

# Legacy alias - used in coin_desk.tasks for backward compatibility
sheet_id = GOOGLE_SHEET_ID

# CRM Integration
WEBHOOK_TOKEN = os.getenv('WEBHOOK_TOKEN')
if not WEBHOOK_TOKEN:
    raise ValueError("WEBHOOK_TOKEN must be set in .env file")

WEBHOOK_TOKEN_2 = os.getenv('WEBHOOK_TOKEN_2')
if not WEBHOOK_TOKEN_2:
    raise ValueError("WEBHOOK_TOKEN_2 must be set in .env file")

# AI/ML Settings
LLM_API_KEY = os.getenv("LLM_API_KEY")

# ==============================================================================
# НАСТРОЙКИ ГОД/ДАТА - централизованное управление
# ==============================================================================

# Текущий год для фильтрации транзакций (меняйте раз в год в .env)
CURRENT_YEAR = int(os.getenv("CURRENT_YEAR", datetime.now().year))

# Временная зона
TIMEZONE = os.getenv("TIMEZONE", "Europe/Moscow")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in .env file. Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'coin_desk',
    'dashboard',
    'django_celery_beat',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coin_counter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coin_counter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / os.getenv("SQLITE_PATH", "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = TIMEZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv("STATIC_URL", "static/")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF trusted origins for production deployments
CSRF_TRUSTED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") 
    if origin.strip()
]

# coin_desk/settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'debug.log',
            'level': 'DEBUG',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,  # храним 5 предыдущих файлов
        },
    },
    'loggers': {
        'coin_desk': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ==============================================================================
# БИЗНЕС-КОНСТАНТЫ
# ==============================================================================

# Категории расходов, которые не учитываются в расчётах
EXCLUDED_COST_CATEGORIES = [
    "Не учитывается",
    "Выручка",
    "Перевод между своими счетами"
]

# Порог similarity для категоризации транзакций по эмбеддингам
EMBEDDING_SIMILARITY_THRESHOLD = float(os.getenv("EMBEDDING_SIMILARITY_THRESHOLD", "0.7"))

# Максимальное количество попыток получения выписки от банка
BANK_STATEMENT_MAX_ATTEMPTS = int(os.getenv("BANK_STATEMENT_MAX_ATTEMPTS", "30"))
