# Generated by Django 5.2.3 on 2025-06-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0003_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorExpenseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('description', models.TextField(blank=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inn_mappings', to='coin_desk.expensecategory')),
            ],
            options={
                'verbose_name': 'Contractor Expense Mapping',
                'verbose_name_plural': 'Contractor Expense Mappings',
            },
        ),
    ]
