# Generated by Django 5.2.3 on 2025-06-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0004_contractorexpensemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='pl_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='coin_desk.plentry'),
        ),
    ]
