# Generated by Django 5.2.3 on 2025-06-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0006_contractor_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='bic',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='contractor',
            name='inn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='expense_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contractorexpensemapping',
            name='inn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contractor_inn',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
