# Generated by Django 5.2.3 on 2025-06-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0007_contractor_bic_contractor_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
