# Generated by Django 5.2.3 on 2025-06-20 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0008_alter_contractor_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(blank=True, choices=[('map', 'По ИНН'), ('default', 'По умолчанию (выручка)'), ('embedding', 'По эмбеддингам')], default=None, max_length=10, null=True, verbose_name='Источник категории'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expense_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='coin_desk.expensecategory'),
        ),
    ]
