# Generated by Django 5.2.3 on 2025-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0009_transaction_category_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
