# Generated by Django 5.2.3 on 2025-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0010_transaction_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
