# Generated by Django 5.2.3 on 2025-06-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0012_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unloaded',
            field=models.BooleanField(default=False),
        ),
    ]
