# Generated by Django 5.2.3 on 2025-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0013_transaction_unloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
