# Generated by Django 5.2.3 on 2025-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0014_transaction_month_transaction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='deal',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='lead',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='lead',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date_modify',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
