# Generated by Django 5.2.3 on 2025-06-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0015_deal_month_deal_year_lead_month_lead_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_and_Deal_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('number_of_deals', models.PositiveSmallIntegerField(default=0)),
                ('number_of_leads', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lead_and_Deal_history',
                'verbose_name_plural': 'Lead_and_Deal_history`s',
            },
        ),
    ]
