# Generated by Django 5.2.3 on 2026-01-23 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coin_desk", "0016_lead_and_deal_history"),
    ]

    operations = [
        # Переименовываем модель (таблица остаётся той же благодаря db_table)
        migrations.RenameModel(
            old_name="Lead_and_Deal_history",
            new_name="LeadAndDealHistory",
        ),
        # Обновляем Meta options
        migrations.AlterModelOptions(
            name="leadanddealhistory",
            options={
                "verbose_name": "История лидов и сделок",
                "verbose_name_plural": "История лидов и сделок",
                "ordering": ["-year", "-month"],
            },
        ),
        # Обновляем verbose_name для полей
        migrations.AlterField(
            model_name="leadanddealhistory",
            name="number_of_deals",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Количество сделок"),
        ),
        migrations.AlterField(
            model_name="leadanddealhistory",
            name="number_of_leads",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Количество лидов"),
        ),
        migrations.AlterModelOptions(
            name="contractor",
            options={
                "ordering": ["name"],
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
            },
        ),
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-date_modify"],
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
            },
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-date_modify"],
                "verbose_name": "Лид",
                "verbose_name_plural": "Лиды",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="expense_category",
        ),
        migrations.AlterField(
            model_name="contractor",
            name="bic",
            field=models.CharField(blank=True, max_length=9, verbose_name="БИК"),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="inn",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="deal",
            name="date_modify",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="ID сделки"
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage_id",
            field=models.CharField(max_length=50, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="date_modify",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_id",
            field=models.CharField(max_length=50, unique=True, verbose_name="ID лида"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.CharField(max_length=20, verbose_name="Счёт"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="batch_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coin_desk.contractor",
                verbose_name="Контрагент",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Счёт контрагента"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor_bank_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Наименование банка"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor_bic",
            field=models.CharField(blank=True, max_length=9, verbose_name="БИК банка"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor_corr_account",
            field=models.CharField(blank=True, max_length=20, verbose_name="Корр.счёт"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="contractor_inn",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ИНН контрагента"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Зачисление",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(db_index=True, verbose_name="Дата операции"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Списание",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expense_category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="coin_desk.expensecategory",
                verbose_name="Категория расходов",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notified",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Уведомлено"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="purpose",
            field=models.TextField(blank=True, verbose_name="Назначение платежа"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="unloaded",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Выгружено"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["year", "month"], name="deal_year_month_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["stage_id"], name="deal_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["date_modify"], name="deal_date_mod_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["year", "month"], name="lead_year_month_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status_id"], name="lead_status_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["date_modify"], name="lead_date_mod_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["date", "contractor"], name="trx_date_contractor_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["year", "month"], name="trx_year_month_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["batch_id"], name="trx_batch_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["notified", "unloaded"], name="trx_status_idx"),
        ),
        migrations.AddIndex(
            model_name="leadanddealhistory",
            index=models.Index(fields=["year", "month"], name="hist_year_month_idx"),
        ),
    ]
