# Generated by Django 5.2.3 on 2026-01-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_desk', '0017_leadanddealhistory_delete_lead_and_deal_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorexpensemapping',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contractorexpensemapping',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inn_mappings', to='coin_desk.expensecategory', verbose_name='Категория расходов'),
        ),
        migrations.AlterField(
            model_name='contractorexpensemapping',
            name='inn',
            field=models.CharField(max_length=20, unique=True, verbose_name='ИНН контрагента'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='pl_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='coin_desk.plentry', verbose_name='Группа PL'),
        ),
        migrations.AlterField(
            model_name='plentry',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterModelTable(
            name='leadanddealhistory',
            table='coin_desk_lead_and_deal_history',
        ),
    ]
